# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 422fbb1582c450d22ebaead2b5a7d8e674967cf241eaf44124f14aba1e80f0e6a6b0869d37158133220df7d338afa49a771ae964e30f3058337f11222cd3e921

test:
  secret_key_base: 518164e33558fb9d4528d21d9abe3566efdde34d1ca4e7dca99e00260477212b5b6ff69ad860bd1f3598a9cc0a22aaad64d93e7949469099d5ec961b59b30729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
